baseURL: https://juansbg.netlify.app
languageCode: en-us
title: Juan
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Take a Look
    subtitle: |-
      THIS IS MY WEBSITE PORTFOLIO TO SHOWCASE SOME OF MY MOST RECENT PROJECTS
    title: Hi, my name is Juan
  blog: {}
  contact:
    address:
      - city: London, NW8
        country: England
        street: Fisherton St.
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: juans.mam2023@london.com
        title: Email
    enable: yes
    phone:
      - phone: (+34) 639 101 127
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      # - icon: fa-twitter
      #   label: Twitter
      #   url: https://www.twitter.com
      # - icon: fa-facebook
      #   label: Facebook
      #   url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/juansbg_/
      - icon: fa-github
        label: GitHub
        url: https://github.com/juansbg
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/juan-sanchez-blanco/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: All Works
        url: works
    # button2:
    #   - name: Log In
    #     url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: about/me
      - name: My CV
        url: about/cv/CV_JUAN_LBS_2022.pdf
      # - name: Elements
      #   url: elements.html
    menu: Menu
    subtitle: 
    title: JUAN'S PORTFOLIO WEBSITE
  tiles:
    enable: yes
    showcase:
      - image: cv_image.jpg
        subtitle: Check out my career journey
        title: MY CV
        url: about/cv/CV_JUAN_LBS_2022.pdf
      - image: about_me.jpg
        subtitle: Find out more about me!
        title: ABOUT ME
        url: about/me
      - image: portfolio1.jpg
        subtitle: Omega Group PLC gender gap analysis
        title: PAY DISCRIMINATION
        url: works/omega
      - image: gdp.jpg
        subtitle: Time series analysis of country GDP
        title: GDP COMPONENTS OVER TIME
        url: works/gdp
  two:
    buttonText: Get to know more!
    enable: yes
    subtitle: "Hi, I'm currently studying a Master's in Analytics and Management at LBS, and in my free time I love to ski, play badminton or watch a scary movie with friends. I also love to play around with AI, and spend my free time building ML models with python!"
    title: Brief summary about me
    url: about
